Update XML layouts to use AndroidX widget classes
Fixed XML layout files that were still referencing deprecated Support library
widget classes, which would cause runtime inflation errors:

1. Toolbar.axml
   - Changed: android.support.v7.widget.Toolbar
   - To: androidx.appcompat.widget.Toolbar

2. Tabbar.axml
   - Changed: android.support.design.widget.TabLayout
   - To: com.google.android.material.tabs.TabLayout

3. Added Material Components package
   - Added Xamarin.Google.Android.Material (1.4.0.2)
   - Required for Material Design widgets including TabLayout

Without these changes, the app would crash with:
  android.view.InflateException: Binary XML file line #X: Error inflating class

All Support library references (code, XML, and packages) are now completely
removed and replaced with AndroidX equivalents.